name: Deploy DocC

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .gitignore

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-26
    env:
      DEVELOPER_DIR: /Applications/Xcode_26.2.0.app/Contents/Developer

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build DocC
        run: |
          xcodebuild docbuild \
            -scheme swift-composition-Package \
            -destination "generic/platform=macOS" \
            -derivedDataPath DerivedData

          ARCHIVES=DerivedData/Build/Products/Debug

          xcrun docc merge \
            $ARCHIVES/Composition.doccarchive \
            $ARCHIVES/CompositionTesting.doccarchive \
            --output-path merged.doccarchive

          xcrun docc process-archive \
            transform-for-static-hosting merged.doccarchive \
            --output-path ./docs \
            --hosting-base-path swift-composition

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs

  deploy:
    runs-on: ubuntu-slim
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: "https://cybozu.github.io/swift-composition/documentation/"

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
